version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8090:8090'
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=flowdb
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  mongodb-data:
    driver: local
